extends: 'spectral:oas'
formats: ['oas3']

rules:
  operation-operationId:
    severity: error
    description: 'Operation must have an operationId'

  no-any-schemas:
    severity: error
    description: "Schemas should not use 'any' type"
    given: '$..schema'
    then:
      field: 'type'
      function: pattern
      functionOptions:
        notMatch: '^any$'

  standard-error-schema:
    severity: error
    description: '4xx/5xx responses should reference a standard error schema'
    given: '$.paths.*.*.responses[?(@property =~ /^(4|5)/)]'
    then:
      function: schema
      functionOptions:
        schema:
          type: object
          properties:
            content:
              type: object
              properties:
                application/json:
                  type: object
                  properties:
                    schema:
                      type: object
                      properties:
                        $ref:
                          type: string
