openapi: 3.0.3
info:
  title: Training API
  version: "1.0.0"
  description: Initial contract stub for Week 6 Finish-to-Green
servers:
  - url: https://api.example.com
paths:
  /posts:
    get:
      operationId: listPosts
      tags: [Posts]
      description: List posts available for SSR display on /posts
      responses:
        '200':
          description: A list of posts
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Post'
        '400':
          $ref: '#/components/responses/ClientVisibleError'
        '404':
          $ref: '#/components/responses/ClientVisibleError'
        '429':
          $ref: '#/components/responses/ClientVisibleError'
        '500':
          description: Server error
components:
  schemas:
    Post:
      type: object
      required: [id, title, body]
      properties:
        id:
          type: string
        title:
          type: string
        body:
          type: string
    ClientVisible4xxError:
      type: object
      required: [code, message]
      properties:
        code:
          type: string
          description: Stable error code
        message:
          type: string
          description: Human-readable error message
        details:
          type: object
          description: Optional error context
  responses:
    ClientVisibleError:
      description: Client-visible 4xx error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ClientVisible4xxError'
