name: Generate package-lock

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  lockfile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Generate lockfile (no install)
        run: npm install --package-lock-only --no-audit --no-fund

      - name: Commit lockfile if changed
        run: |
          if git diff --quiet -- package-lock.json; then
            echo "No lockfile changes";
          else
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add package-lock.json
            git commit -m "chore(lockfile): generate real package-lock.json via CI"
            git push
          fi


