name: Mirror to Public Repo

# Prevent overlapping runs per ref
concurrency:
  group: mirror-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - master
    tags:
      - '*'
  workflow_dispatch:
    inputs:
      mirror_repo_slug:
        description: "Destination repo as owner/repo (overrides variables)"
        required: false
        type: string
      mirror_repo_url:
        description: "Destination repo full URL (https or ssh)"
        required: false
        type: string

permissions:
  contents: read

jobs:
  mirror:
    name: Push all refs to public mirror
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Validate configuration (PAT only)
        env:
          INPUT_SLUG: ${{ inputs.mirror_repo_slug }}
          INPUT_URL: ${{ inputs.mirror_repo_url }}
          VAR_SLUG: ${{ vars.MIRROR_REPO_SLUG }}
          MIRROR_PAT: ${{ secrets.MIRROR_PAT }}
        shell: bash
        run: |
          set -euo pipefail
          MIRROR_REPO_SLUG="${INPUT_SLUG:-${VAR_SLUG:-}}"
          MIRROR_URL="${INPUT_URL:-}"

          if [ -z "${MIRROR_REPO_SLUG}" ] && [ -n "${MIRROR_URL}" ]; then
            # Derive owner/repo from URL
            tmp="${MIRROR_URL}"
            tmp="${tmp#https://github.com/}"
            tmp="${tmp#http://github.com/}"
            tmp="${tmp#git@github.com:}"
            tmp="${tmp%.git}"
            MIRROR_REPO_SLUG="${tmp}"
          fi

          if [ -z "${MIRROR_REPO_SLUG}" ]; then
            echo "ERROR: Destination not configured. Provide one of:"
            echo "- vars.MIRROR_REPO_SLUG (owner/repo)"
            echo "- workflow_dispatch input mirror_repo_slug or mirror_repo_url" >&2
            exit 1
          fi

          if [ -z "${MIRROR_PAT}" ]; then
            echo "ERROR: secrets.MIRROR_PAT is not set (required for PAT mirroring)." >&2
            exit 1
          fi
          echo "Resolved MIRROR_REPO_SLUG=${MIRROR_REPO_SLUG}"
          echo "slug=${MIRROR_REPO_SLUG}" >> "$GITHUB_OUTPUT"
          echo "auth=https" >> "$GITHUB_OUTPUT"
        id: validate

      - name: Configure git
        shell: bash
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Remove leftover auth headers for github.com
        shell: bash
        run: |
          # Ensure pushes to mirror use MIRROR_PAT rather than GITHUB_TOKEN injected by checkout
          git config --local --unset-all http.https://github.com/.extraheader || true

      # No remote needed for PAT; we push via fully-qualified https URL

      # PAT preflight uses Basic Authorization header
      - name: Preflight auth to mirror (HTTPS)
        if: steps.validate.outputs.auth == 'https'
        shell: bash
        env:
          MIRROR_REPO_SLUG: ${{ steps.validate.outputs.slug }}
          MIRROR_PAT: ${{ secrets.MIRROR_PAT }}
        run: |
          set -euo pipefail
          PAT_CLEAN="$(printf '%s' "${MIRROR_PAT}" | tr -d '\r\n')"
          AUTH_B64="$(printf 'x-access-token:%s' "${PAT_CLEAN}" | base64 -w 0)"
          export GIT_TERMINAL_PROMPT=0
          export GIT_ASKPASS=:
          git -c credential.helper= -c http.extraheader="Authorization: Basic ${AUTH_B64}" ls-remote "https://github.com/${MIRROR_REPO_SLUG}.git" >/dev/null

      - name: Mirror push (branches and tags)
        if: steps.validate.outputs.auth == 'https'
        shell: bash
        env:
          MIRROR_REPO_SLUG: ${{ steps.validate.outputs.slug }}
          MIRROR_PAT: ${{ secrets.MIRROR_PAT }}
        run: |
          set -euo pipefail
          git fetch --prune origin
          PAT_CLEAN="$(printf '%s' "${MIRROR_PAT}" | tr -d '\r\n')"
          PUSH_URL="https://x-access-token:${PAT_CLEAN}@github.com/${MIRROR_REPO_SLUG}.git"
          export GIT_TERMINAL_PROMPT=0
          export GIT_ASKPASS=/bin/echo
          export GIT_SSH_ASKPASS=/bin/echo
          # Ensure no credential helper interferes
          git config --global --unset-all credential.helper || true
          # Clear any extra headers and push using embedded token URL
          git -c credential.helper= \
              -c core.askPass=/bin/echo \
              -c credential.interactive=never \
              -c credential.useHttpPath=true \
              -c http.extraheader= \
              -c http.https://github.com/.extraheader= \
              push --prune --mirror "${PUSH_URL}"
