name: Mirror to Public

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - 'patrick/**'
    tags:
      - '*'

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Check secret present
        run: |
          if [ -z "${{ secrets.MIRROR_TOKEN }}" ]; then
            echo "ERROR: MIRROR_TOKEN is missing."
            echo "Add it in: Settings > Secrets and variables > Actions > New repository secret"
            exit 1
          fi

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Configure git
        run: |
          git config user.name "ci-mirror-bot"
          git config user.email "ci-mirror-bot@users.noreply.github.com"

      - name: Add public mirror remote
        env:
          TOKEN: ${{ secrets.MIRROR_TOKEN }}
        run: |
          # Replace ORG and REPO_PUBLIC (Cursor: substitute from user)
          git remote add mirror https://x-access-token:${TOKEN}@github.com/Maximus-Technologies-Uganda/maximus-training-patrick-mirror.git

      - name: Fetch all branches and tags from origin
        run: |
          set -e
          git fetch --prune origin +refs/heads/*:refs/remotes/origin/* +refs/tags/*:refs/tags/*

      - name: Push all branches and tags to mirror
        run: |
          set -e
          # Mirror branches (prune removed branches) from remote-tracking refs
          git push --force --prune mirror +refs/remotes/origin/*:refs/heads/*
          # Mirror tags (prune removed tags)
          git push --force --prune mirror +refs/tags/*:refs/tags/*

      - name: Summary
        run: |
          echo "Mirrored branches:"
          git for-each-ref --format='%(refname:short)' refs/remotes/origin/ | sed 's#^origin/##'
          echo "Mirrored tags:"
          git tag --list


