name: PR requires Linear reference

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]

jobs:
  require-linear-reference:
    name: Require Linear reference
    # Run only for non-draft PRs in private repositories (avoids mirror/public)
    if: ${{ !github.event.pull_request.draft && github.event.repository.private == true }}
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    steps:
      - name: Check PR title/body for Linear reference
        shell: bash
        env:
          PR_TITLE: ${{ github.event.pull_request.title || '' }}
          PR_BODY: ${{ github.event.pull_request.body || '' }}
        run: |
          if printf '%s %s' "$PR_TITLE" "$PR_BODY" | grep -Eiq '(LIN-[0-9]+|Linear[- ]?[0-9]+)'; then
            echo "Linear reference found."
          else
            echo "::error::PR must reference a Linear issue (e.g., LIN-123) in title or body."
            exit 1
          fi