name: Quality Gate
on:
  pull_request:

jobs:
  gate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Node setup
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install (best-effort)
        run: |
          npm ci || echo "No lockfile or npm project; skipping"

      - name: Tests with coverage (best-effort)
        run: |
          npx jest --coverage || echo "Jest missing or tests failed; continuing"

      - name: Lint (best-effort)
        run: |
          npx eslint . || echo "ESLint missing or failed; continuing"

      - name: PASS/FAIL summary (informational)
        run: |
          FAIL=0
          [ -f package.json ] || FAIL=1
          [ -d coverage ] || FAIL=1
          echo "Quality Gate (informational): $([ $FAIL -eq 0 ] && echo PASS || echo FAIL)"
          echo "Criteria checked:"
          echo "- package.json present"
          echo "- coverage folder exists (indicates tests ran)"
          exit 0


