name: Quality Gate

on:
  push:
    paths:
      - 'frontend/**'
      - 'frontend-next/**'
      - 'api/**'
      - '.github/workflows/quality-gate.yml'
  pull_request:
    paths:
      - 'frontend/**'
      - 'frontend-next/**'
      - 'api/**'
      - '.github/workflows/quality-gate.yml'

jobs:
  install-root-deps:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: package-lock.json
      - name: Install root dependencies
        shell: bash
        run: |
          set -e
          npm config set audit false --location=project
          npm config set fund false --location=project
          # Use npm install for better workspace compatibility
          echo "Installing root and workspace dependencies"
          npm install --no-audit --no-fund

  frontend-next-coverage:
    needs: install-root-deps
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Install dependencies
        shell: bash
        run: |
          set -e
          npm config set audit false --location=project
          npm config set fund false --location=project
          # Install root and workspace dependencies
          npm install --no-audit --no-fund
          # Ensure frontend-next has its dependencies
          cd frontend-next
          npm ci

      - name: Run frontend-next tests with coverage
        working-directory: frontend-next
        run: npm run test:ci

      - name: Upload frontend-next coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-frontend-next
          path: |
            frontend-next/coverage/**

      - name: Add coverage to job summary
        if: always()
        working-directory: frontend-next
        shell: bash
        run: |
          echo "### frontend-next Coverage Summary" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo '```json' >> "$GITHUB_STEP_SUMMARY"
          if [ -f coverage/coverage-summary.json ]; then
            cat coverage/coverage-summary.json >> "$GITHUB_STEP_SUMMARY"
          else
            echo '{}' >> "$GITHUB_STEP_SUMMARY"
          fi
          echo '' >> "$GITHUB_STEP_SUMMARY"
          echo '```'

      - name: Read coverage summary
        id: coverage_frontend_next
        run: |
          node - <<'NODE'
          const fs = require('fs');
          const path = require('path');
          const summaryPath = path.join(process.cwd(), 'frontend-next', 'coverage', 'coverage-summary.json');
          if (!fs.existsSync(summaryPath)) {
            console.error('ERROR: Coverage summary not found at frontend-next/coverage/coverage-summary.json. Ensure Vitest runs with coverage.');
            try {
              console.log('Listing frontend-next/coverage directory for diagnostics:');
              console.log(fs.readdirSync(path.join(process.cwd(), 'frontend-next', 'coverage')).join('\n'));
            } catch (e) {
              console.log('No coverage directory present.');
            }
            process.exit(1);
          }
          let summary = null;
          try { summary = JSON.parse(fs.readFileSync(summaryPath, 'utf8')); }
          catch (e) {
            console.error('ERROR: Failed to parse frontend/coverage/coverage-summary.json:', e.message);
            process.exit(1);
          }
          function statementsPct(summary){
            if (!summary || !summary.total || !summary.total.statements) return 'no files collected';
            const t = summary.total.statements;
            if (typeof t.total === 'number' && t.total === 0) return 'no files collected';
            if (typeof t.pct === 'number') return String(t.pct) + '%';
            return 'no files collected';
          }
          const rows = [['Target','Statements %'], ['frontend-next', statementsPct(summary)]];
          const pad = (arr, widths) => arr.map((c,i)=>String(c).padEnd(widths[i])).join(' | ');
          const widths = rows[0].map((_,i)=>Math.max(...rows.map(r=>String(r[i]).length)));
          let table = `| ${pad(rows[0], widths)} |\n| ${widths.map(w=>'-'.repeat(w)).join(' | ')} |\n`;
          for (let i=1;i<rows.length;i++){ table += `| ${pad(rows[i], widths)} |\n`; }
          fs.writeFileSync('coverage-table.md', table);
          console.log(table);
          NODE

      - name: Comment coverage on PR
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: coverage-report-frontend-next
          path: coverage-table.md

  api-coverage:
    needs: install-root-deps
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'package-lock.json'

      - name: Install dependencies
        shell: bash
        run: |
          set -e
          npm config set audit false --location=project
          npm config set fund false --location=project
          # Install root and workspace dependencies
          npm install --no-audit --no-fund
          # Ensure API has its dependencies
          cd api
          npm ci

      - name: Debug available api scripts
        run: |
          node -e "const p=require('./api/package.json');console.log('scripts',p.scripts)" | cat
          ls -la api
          ls -la api/node_modules/.bin || true
          node -e "console.log(process.cwd())"

      - name: Run API tests with coverage (in-memory repo)
        working-directory: api
        env:
          POSTS_REPOSITORY: inmemory
        run: npm run test:ci

      - name: Upload API coverage artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-api
          path: |
            api/coverage/**

      - name: Add coverage to job summary
        if: always()
        working-directory: api
        shell: bash
        run: |
          echo "### API Coverage Summary" >> "$GITHUB_STEP_SUMMARY"
          echo "" >> "$GITHUB_STEP_SUMMARY"
          echo '```json' >> "$GITHUB_STEP_SUMMARY"
          if [ -f coverage/coverage-summary.json ]; then
            cat coverage/coverage-summary.json >> "$GITHUB_STEP_SUMMARY"
          else
            echo '{}' >> "$GITHUB_STEP_SUMMARY"
          fi
          echo '' >> "$GITHUB_STEP_SUMMARY"
          echo '```'

      - name: Read coverage summary
        id: api_coverage
        run: |
          node - <<'NODE'
          const fs = require('fs');
          const path = require('path');
          const summaryPath = path.join(process.cwd(), 'api', 'coverage', 'coverage-summary.json');
          if (!fs.existsSync(summaryPath)) {
            console.error('ERROR: Coverage summary not found at api/coverage/coverage-summary.json. Ensure Jest runs with coverage.');
            try {
              console.log('Listing api/coverage directory for diagnostics:');
              console.log(fs.readdirSync(path.join(process.cwd(), 'api', 'coverage')).join('\n'));
            } catch (e) {
              console.log('No coverage directory present.');
            }
            process.exit(1);
          }
          let summary = null;
          try { summary = JSON.parse(fs.readFileSync(summaryPath, 'utf8')); }
          catch (e) {
            console.error('ERROR: Failed to parse api/coverage/coverage-summary.json:', e.message);
            process.exit(1);
          }
          function statementsPct(summary){
            if (!summary || !summary.total || !summary.total.statements) return 'no files collected';
            const t = summary.total.statements;
            if (typeof t.total === 'number' && t.total === 0) return 'no files collected';
            if (typeof t.pct === 'number') return String(t.pct) + '%';
            return 'no files collected';
          }
          const rows = [['Target','Statements %'], ['API', statementsPct(summary)]];
          const pad = (arr, widths) => arr.map((c,i)=>String(c).padEnd(widths[i])).join(' | ');
          const widths = rows[0].map((_,i)=>Math.max(...rows.map(r=>String(r[i]).length)));
          let table = `| ${pad(rows[0], widths)} |\n| ${widths.map(w=>'-'.repeat(w)).join(' | ')} |\n`;
          for (let i=1;i<rows.length;i++){ table += `| ${pad(rows[i], widths)} |\n`; }
          fs.writeFileSync('api-coverage-table.md', table);
          console.log(table);
          NODE

      - name: Comment coverage on PR
        if: github.event_name == 'pull_request'
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: api-coverage-report
          path: api-coverage-table.md

  aggregate-coverage:
    name: Aggregate monorepo coverage and summarize
    runs-on: ubuntu-latest
    needs: [frontend-next-coverage, api-coverage]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install root deps for scripts
        run: |
          npm config set audit false --location=project
          npm config set fund false --location=project
          npm install --no-audit --no-fund --omit=optional

      - name: Download coverage artifacts from prior jobs
        uses: actions/download-artifact@v4
        with:
          path: _dl
        continue-on-error: true

      - name: Move downloaded coverage into expected locations
        shell: bash
        run: |
          # Place any downloaded coverage into their package directories if needed
          # We only rely on local runs here; if artifacts are absent, we proceed.
          mkdir -p frontend-next/coverage api/coverage || true
          # If upstream jobs also wrote coverage directly in the workspace, nothing to do
          # Otherwise, attempt to copy from artifacts
          if [ -d "_dl/coverage-frontend-next/frontend-next/coverage" ]; then
            cp -R _dl/coverage-frontend-next/frontend-next/coverage/. frontend-next/coverage/ || true
          fi
          if [ -d "_dl/coverage-api/api/coverage" ]; then
            cp -R _dl/coverage-api/api/coverage/. api/coverage/ || true
          fi

      - name: Normalize coverage (monorepo)
        run: npm run coverage:normalize

      - name: Summarize coverage totals (monorepo and frontend-next)
        shell: bash
        run: |
          echo "### Monorepo Coverage Totals" >> "$GITHUB_STEP_SUMMARY"
          echo '' >> "$GITHUB_STEP_SUMMARY"
          echo '```json' >> "$GITHUB_STEP_SUMMARY"
          if [ -f coverage/coverage-summary.json ]; then
            cat coverage/coverage-summary.json >> "$GITHUB_STEP_SUMMARY"
          else
            echo '{"note":"no aggregated coverage found"}' >> "$GITHUB_STEP_SUMMARY"
          fi
          echo '' >> "$GITHUB_STEP_SUMMARY"
          echo '```' >> "$GITHUB_STEP_SUMMARY"

          echo "\n### frontend-next Coverage Totals" >> "$GITHUB_STEP_SUMMARY"
          echo '' >> "$GITHUB_STEP_SUMMARY"
          echo '```json' >> "$GITHUB_STEP_SUMMARY"
          if [ -f frontend-next/coverage/coverage-summary.json ]; then
            cat frontend-next/coverage/coverage-summary.json >> "$GITHUB_STEP_SUMMARY"
          else
            echo '{"note":"no frontend-next coverage found"}' >> "$GITHUB_STEP_SUMMARY"
          fi
          echo '' >> "$GITHUB_STEP_SUMMARY"
          echo '```' >> "$GITHUB_STEP_SUMMARY"